export const queryKeys = {
    posts: ["posts"],
    post: (id) => ["post", id],
    sports: ["sports"],
    positions: ["positions"],
    positionsBySport: (sportId) => ["positions", "bySport", sportId],
    locations: ["locations"],
    feed: ["posts", "feed"],
    replies: (id) => ["replies", id],
    friendsFeed: ['friendsFeed'],
    advertisements: ["advertisements"],
    recommendedAdvertisements: ["advertisements", "recommended"],
    applications: (advertisementId) => ["applications", advertisementId],
    myApplications: ["myApplications"],
    suggestedPeople: ["suggestedPeople"],
    suggestedClubs: ["suggestedClubs"],
    userProfile: (nickname) => ["userProfile", nickname],
    userPosts: (nickname, offset, limit) => ["userPosts", nickname, offset, limit],
    chats: ["chats"],
    chat: (id) => ["chats", id],
    messages: (chatId) => ["messages", chatId],
    notifications: ["notifications"],
    notificationsUnread: ["notifications", "unread"],
    friendRequestsIncoming: ["friendRequests", "incoming"],
}